### ISSUE TITLE
Log-in without Selenium

### ISSUE THREAD

**Issue by ghost** [topongo/nuvola#2]
Importa BeautifulSoup (bs4) <- Non ne sono sicuro, non aggiorno il mio codice da quando è uscita la api mesi fa.
Importa lxml, lxml.etree, lxml.html

Snippet:

```
import lxml.html as html
from bs4 import BeautifulSoup
import lxml.etree as etree

login_page = requests.get("https://nuvola.madisoft.it/login")
csrf_token = html.fromstring( login_page.content ).xpath( "//input[@name='_csrf_token']/@value" )

check_login = requests.post("https://nuvola.madisoft.it/login_check",
data= {"_csrf_token": csrf_token, "_username": self.username, "_password": self.password},
headers= {"Origin": "https://nuvola.madisoft.it", "Referer": "https://nuvola.madisoft.it/login", "Cookie": f"nuvola
{login_page.cookies['nuvola']}"})

(ho ricreato l'auth flow del browser)

datalogin = requests.get('https://nuvola.madisoft.it/api-studente/v1/login-from-web').json()
datalogin['token']

```

Poi da datalogin ottieni il token

**Comment by topongo** [comment]
Hi, sorry, I know we're both italian but I prefer using english here on git so everyone can understand properly.
I'm sorry also for being extremely late... I'm passing through hard times: exams and other infinite stuff.

Well now about the issue, I've tried all the afternoon to make it work using only simple request: I'm trying to isolate the bare minimum for a funcioning login. For bare minimum I mean avoiding the use of javascript during login, but right now seems impossible at least...

I'm trying to mimic the browser behaviour (copy-paste curl requests and changing the headers with a new pair of nuvola and csrf tokens) but nothing, it seems that magically the browser is able to handle the operation and python/cURL simply don't... I think some part of the completly obscure javascript in someone of the pages in the login process is doing some sort of client-sided challange in a cloudflare style, hope I'm wrong elsewere we're screwed (if so we're stuck using a webdriver).

Tonight if I find some time I'll try disabling javascript in chrome/firefox and try like that.

If you want to make some further investigation, I'll explaing the details of my latest testings and what I'm currently aware of.

Cheers

**Comment by ghost** [comment]
> Hi, sorry, I know we're both italian but I prefer using english here on git so everyone can understand properly.
> I'm sorry also for being extremely late... I'm passing through hard times: exams and other infinite stuff.
> 
> Well now about the issue, I've tried all the afternoon to make it work using only simple request: I'm trying to isolate the bare minimum for a funcioning login. For bare minimum I mean avoiding the use of javascript during login, but right now seems impossible at least...
> 
> I'm trying to mimic the browser behaviour (copy-paste curl requests and changing the headers with a new pair of nuvola and csrf tokens) but nothing, it seems that magically the browser is able to handle the operation and python/cURL simply don't... I think some part of the completly obscure javascript in someone of the pages in the login process is doing some sort of client-sided challange in a cloudflare style, hope I'm wrong elsewere we're screwed (if so we're stuck using a webdriver).
> 
> Tonight if I find some time I'll try disabling javascript in chrome/firefox and try like that.
> 
> If you want to make some further investigation, I'll explaing the details of my latest testings and what I'm currently aware of.
> 
> Cheers

Do you have any contact channel? I may be able to help you a bit

**Comment by topongo** [comment]
> Do you have any contact channel? I may be able to help you a bit
here's my discord topongo#0420

**Comment by topongo** [comment]
>
> Do you have any contact channel? I may be able to help you a bit

Here's my discord `topongo#0420`

**Comment by topongo** [comment]
I've talked privately with @SammySM and we figured out a proper solution, finally selenium is out of the way! Just pushed the new updated version: a9aead741ad12a2fc22830ad19e3d221790e4971
